OrgUnit.create!(:text => 'Presidencia')
OrgUnit.create!(:text => 'Coordinación Servicios Profesionales')
srvs_prof = OrgUnit.create!(:text => 'Servicios Profesionales')
OrgUnit.create!(:text => 'Turismo', :parent_id => srvs_prof.id)
OrgUnit.create!(:text => 'Inscripciones y Publicaciones', :parent_id => srvs_prof.id)
OrgUnit.create!(:text => 'Subsidios, Seguro de Vida y Convenios', :parent_id => srvs_prof.id)
OrgUnit.create!(:text => 'Administración de Productos', :parent_id => srvs_prof.id)
OrgUnit.create!(:text => 'Marketing')
OrgUnit.create!(:text => 'Consejito')
OrgUnit.create!(:text => 'EDICON')
matric = OrgUnit.create!(:text => 'Legalizaciones, Matrículas y Control')
OrgUnit.create!(:text => 'Legalizaciones', :parent_id => matric.id)
OrgUnit.create!(:text => 'Matrículas', :parent_id => matric.id)
OrgUnit.create!(:text => 'Vigilancia Profesional', :parent_id => matric.id)
salud = OrgUnit.create!(:text => 'Consejo Salud')
OrgUnit.create!(:text => 'Sistema SIMECO', :parent_id => salud.id)
OrgUnit.create!(:text => 'SAP', :parent_id => salud.id)
OrgUnit.create!(:text => 'Centro Médico', :parent_id => salud.id)
OrgUnit.create!(:text => 'Coordinación Temas Académicos')
tecnica = OrgUnit.create!(:text => 'Técnica')
OrgUnit.create!(:text => 'Asesores', :parent_id => tecnica.id)
OrgUnit.create!(:text => 'Comisiones', :parent_id => tecnica.id)
OrgUnit.create!(:text => 'Congresos y Eventos', :parent_id => tecnica.id)
OrgUnit.create!(:text => 'Administración de RCyT', :parent_id => tecnica.id)
OrgUnit.create!(:text => 'Sindicatura Concursal', :parent_id => tecnica.id)
OrgUnit.create!(:text => 'Escuela de Educación Continuada')
OrgUnit.create!(:text => 'Instituto de Ciencias Económicas')
OrgUnit.create!(:text => 'Centro de Información Bibliográfica')
OrgUnit.create!(:text => 'Centro de Mediación')
admin = OrgUnit.create!(:text => 'Administración')
OrgUnit.create!(:text => 'Contaduría', :parent_id => admin.id)
OrgUnit.create!(:text => 'Tesorería', :parent_id => admin.id)
OrgUnit.create!(:text => 'Correspondencia', :parent_id => admin.id)
OrgUnit.create!(:text => 'Compras', :parent_id => admin.id)
OrgUnit.create!(:text => 'Mesa de Entradas', :parent_id => admin.id)
rrhh = OrgUnit.create!(:text => 'RRHH y Servicios')
OrgUnit.create!(:text => 'Administración de RRHH', :parent_id => rrhh.id)
OrgUnit.create!(:text => 'Vigilancia', :parent_id => rrhh.id)
OrgUnit.create!(:text => 'Servicios Generales', :parent_id => rrhh.id)
OrgUnit.create!(:text => 'Servicio de empleo', :parent_id => rrhh.id)
OrgUnit.create!(:text => 'Orientación Laboral', :parent_id => rrhh.id)
it = OrgUnit.create!(:text => 'Sistemas')
OrgUnit.create!(:text => 'Desarrollo', :parent_id => it.id)
OrgUnit.create!(:text => 'Base de Datos', :parent_id => it.id)
OrgUnit.create!(:text => 'Redes e Internet', :parent_id => it.id)
OrgUnit.create!(:text => 'Trivia', :parent_id => it.id)
OrgUnit.create!(:text => 'Auditoria y Control de Gestión')
OrgUnit.create!(:text => 'Relaciones Públicas')
rel = OrgUnit.create!(:text => 'Relaciones Institucionales')
OrgUnit.create!(:text => 'Sec. de Mesa y Consejo Directivo', :parent_id => rel.id)
OrgUnit.create!(:text => 'Desarrollo Profesional', :parent_id => rel.id)
OrgUnit.create!(:text => 'Seguridad Informática')
OrgUnit.create!(:text => 'Asuntos Legales')
OrgUnit.create!(:text => 'Tribunal Arbitral')
OrgUnit.create!(:text => 'Organización y Métodos')
OrgUnit.create!(:text => 'Gestión de la Calidad')
