pr0 = ProjectName.find_or_create_by_text("Asesoramiento Profesional")
pr1 = ProjectName.find_or_create_by_text("Registro de Consultas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Auxiliares de la justicia")
pr1 = ProjectName.find_or_create_by_text("Peritos", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Auxiliares de la justicia")
pr1 = ProjectName.find_or_create_by_text("Síndicos", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Bancos")
pr1 = ProjectName.find_or_create_by_text("Administracion (ABM)", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Bancos")
pr1 = ProjectName.find_or_create_by_text("Ingreso/Transmision de mvtos", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Capacitación")
pr1 = ProjectName.find_or_create_by_text("Cobranzas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Capacitación")
pr1 = ProjectName.find_or_create_by_text("Inscripción", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administración", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Capacitación")
pr1 = ProjectName.find_or_create_by_text("Inscripción", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consultas/listados", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Capacitación")
pr1 = ProjectName.find_or_create_by_text("Inscripción ", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Ciclos Tributarios WEB", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Capacitación")
pr1 = ProjectName.find_or_create_by_text("Planificación de cursos", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administración", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Capacitación")
pr1 = ProjectName.find_or_create_by_text("Planificación de cursos", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consultas/listados", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Capacitación")
pr1 = ProjectName.find_or_create_by_text("Planificación de cursos", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consulta próximos cursos", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Cobranzas")
pr1 = ProjectName.find_or_create_by_text("Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Cobranzas")
pr1 = ProjectName.find_or_create_by_text("Caja", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Cobranzas")
pr1 = ProjectName.find_or_create_by_text("Tesorería", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Comisiones")
pr1 = ProjectName.find_or_create_by_text("Administracion", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Comisiones")
pr1 = ProjectName.find_or_create_by_text("Consultas/listados", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("18 Congreso", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Inscripción CABA", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("18 Congreso", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Inscripción provincias", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("Cobranza", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("Inscripción", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administración", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("Inscripción", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consultas/listados/transferencias", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("Inscripción por Internet", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("Planificación", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administración", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Congresos")
pr1 = ProjectName.find_or_create_by_text("Planificación", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consultas/listados/transferencias", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Facturación Unificada")
pr1 = ProjectName.find_or_create_by_text("Consultas/transferencias", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Facturación Unificada")
pr1 = ProjectName.find_or_create_by_text("Generación FC, NCR, ND", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Facturación Unificada")
pr1 = ProjectName.find_or_create_by_text("Venta de productos", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Foros")
pr1 = ProjectName.find_or_create_by_text("Foro WEB", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Foros")
pr1 = ProjectName.find_or_create_by_text("Inscripción a foros", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Honorarios Mínimos")
pr0 = ProjectName.find_or_create_by_text("Internet")
pr1 = ProjectName.find_or_create_by_text("Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Internet")
pr1 = ProjectName.find_or_create_by_text("Cobranzas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Internet")
pr1 = ProjectName.find_or_create_by_text("Facturación", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Internet")
pr1 = ProjectName.find_or_create_by_text("Suscripción", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Cobranzas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Cuenta Corriente", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administración", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Cuenta Corriente", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consulta, listados y estadísticas", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Cuenta Corriente", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Facturación", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("DGR", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("F780", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Presentación", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("F780", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Transferencia AFIP", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("F780", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Convenio", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("F780", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administración", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Gestor tributario", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Informe Confidencial", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Listados, Estadísticas y Consultas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Legalizaciones")
pr1 = ProjectName.find_or_create_by_text("Registración y Verificación", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Baja y Rehabilitación", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administracion (ABM)", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Base de Datos de Calles", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consulta a la Base", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Base de Datos de Calles", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Altas y Modificaciones a la Base", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Cambio de domicilio", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Carga de CBUs", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Certificados", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administrador de consorcio", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Certificados", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Constancia de estampilla", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Certificados", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Inscripción, sanción y libre deuda", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Consultas, Listados, Estadísticas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Credencial profesional", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Listado y consulta ", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Credencial profesional", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Importación de imágenes de puestos offline", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Credencial profesional", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Emisión", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Impresión de Notas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Matriculados")
pr1 = ProjectName.find_or_create_by_text("Referentes y referidos", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Mesa de Entrada")
pr1 = ProjectName.find_or_create_by_text("Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Mesa de Entrada")
pr1 = ProjectName.find_or_create_by_text("Consultas/listados", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Nuevos Matriculados")
pr1 = ProjectName.find_or_create_by_text("DEP", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Nuevos Matriculados")
pr1 = ProjectName.find_or_create_by_text("Expedientes", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Nuevos Matriculados")
pr1 = ProjectName.find_or_create_by_text("Folio", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Nuevos Matriculados")
pr1 = ProjectName.find_or_create_by_text("Resoluciones", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Personal")
pr1 = ProjectName.find_or_create_by_text("Administración de datos y áreas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("RCyT")
pr1 = ProjectName.find_or_create_by_text("Actualidad Tributaria", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("RCyT")
pr1 = ProjectName.find_or_create_by_text("Administración de RCyT", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("RCyT")
pr1 = ProjectName.find_or_create_by_text("Inscripcion x Internet", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("RCyT")
pr1 = ProjectName.find_or_create_by_text("Videos arancelados", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Registro de estudiantes")
pr1 = ProjectName.find_or_create_by_text("Inscripción", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Reserva de turnos")
pr0 = ProjectName.find_or_create_by_text("Resoluciones de Mesa Directiva")
pr1 = ProjectName.find_or_create_by_text("Administracion (ABM)", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Resoluciones de Mesa Directiva")
pr1 = ProjectName.find_or_create_by_text("Consultas/Listados", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Seguro de Vida")
pr1 = ProjectName.find_or_create_by_text("Facturación", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("SFAP")
pr1 = ProjectName.find_or_create_by_text("Exportación a Federación", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("SFAP")
pr1 = ProjectName.find_or_create_by_text("Listado y Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Sistema Contable")
pr1 = ProjectName.find_or_create_by_text("Interfase", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Sistema Contable")
pr1 = ProjectName.find_or_create_by_text("Plan de cuentas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Sistema Medico")
pr1 = ProjectName.find_or_create_by_text("Tarjeta Integrar", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Administrador de Mails", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Administración", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Encuestas genericas x Internet", :parent_id => pr0)
pr2 = ProjectName.create(:text => "encustas", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("gestión de emails", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Antispam", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("gestión de emails", :parent_id => pr0)
pr2 = ProjectName.create(:text => "CambioEmailPassword", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Internet", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Webmail front-end", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Intranet", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Archivos protegidos de Intranet", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Intranet", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Consultas a la base de datos", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Intranet", :parent_id => pr0)
pr2 = ProjectName.create(:text => "Menú Intranet", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Login de Matriculados", :parent_id => pr0)
pr2 = ProjectName.create(:text => "login", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Pantalla con envío de email", :parent_id => pr0)
pr2 = ProjectName.create(:text => "enviaEmailGenerico", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Pantalla de confirmación", :parent_id => pr0)
pr2 = ProjectName.create(:text => "confirmaClick", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("Pantalla de ingreso tarjeta de crédito", :parent_id => pr0)
pr2 = ProjectName.create(:text => "tarjeta", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("procesos mantenimiento de tablas", :parent_id => pr0)
pr2 = ProjectName.create(:text => "BorrarEmailUnknownDaemon", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("procesos mantenimiento de tablas", :parent_id => pr0)
pr2 = ProjectName.create(:text => "BorraEnvioMailDaemon", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Sistemas")
pr1 = ProjectName.find_or_create_by_text("procesos mantenimiento de tablas", :parent_id => pr0)
pr2 = ProjectName.create(:text => "SessionEraser", :parent_id => pr1)
pr0 = ProjectName.find_or_create_by_text("Subsidios")
pr1 = ProjectName.find_or_create_by_text("Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Subsidios")
pr1 = ProjectName.find_or_create_by_text("Consultas/listados", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Subsidos")
pr1 = ProjectName.find_or_create_by_text("Devengamiento", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Subsidos")
pr1 = ProjectName.find_or_create_by_text("Interfase Bejerman", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Tarjetas Consetel")
pr1 = ProjectName.find_or_create_by_text("Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Tarjetas Consetel")
pr1 = ProjectName.find_or_create_by_text("Cobranzas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Tarjetas Consetel")
pr1 = ProjectName.find_or_create_by_text("Transferencia", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Tribunal  de Etica Profesional")
pr1 = ProjectName.find_or_create_by_text("Administración", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Administracion (ABM)", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Boletín", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Calendario impositivo", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Cobranzas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Consultas/Listados", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Cuenta Corriente", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Débito Automático", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Encuesta", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Estadísticas", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Facturación", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Historial de Trivia", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Login", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Pases libres", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Suscripción", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Trivia")
pr1 = ProjectName.find_or_create_by_text("Trivia CD", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Turismo")
pr1 = ProjectName.find_or_create_by_text("Listas de casamiento", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Ventas varias")
pr1 = ProjectName.find_or_create_by_text("Cena", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Ventas varias")
pr1 = ProjectName.find_or_create_by_text("Día de campo", :parent_id => pr0)
pr0 = ProjectName.find_or_create_by_text("Ventas varias")
pr1 = ProjectName.find_or_create_by_text("Truco", :parent_id => pr0)
